### ISSUE TITLE
yes

### ISSUE THREAD

**Issue by caneleex** [niklas2810/my-discord-butler#3]
yes

**Comment by markozajc** [comment]
canelex did you forgot to take the pills

**Comment by ArchdukeLiamus** [comment]
yes

**Comment by BomBardyGamer** [comment]
what dis

**Comment by caneleex** [comment]
> canelex did you forget to take the pills

yes

**Comment by caneleex** [comment]
> yes

yes

**Comment by caneleex** [comment]
> what dis

yes

**Comment by markozajc** [comment]
Arch Linux

    Home
    Packages
    Forums
    Wiki
    Bugs
    Security
    AUR
    Download

    Index
    Rules
    Search
    Register
    Login

You are not logged in.

    Topics: Active | Unanswered 

    Index
    » Newbie Corner
    » how i can "apt-get autoremove" and "autoclean" like debian based?

Pages: 1

Topic closed
#1 2008-06-11 08:50:21

indoultimate
    Member
    Registered: 2008-06-10
    Posts: 9

how i can "apt-get autoremove" and "autoclean" like debian based?

hi, i would like to know how to do "apt-get autoremove" and "apt-get autoclean" like debian based linux in arch for cleaning the system?
thanks you for this community....

Offline
#2 2008-06-11 08:53:38

wonder
    Developer
    From: Bucharest, Romania
    Registered: 2006-07-05
    Posts: 5,937
    Website

Re: how i can "apt-get autoremove" and "autoclean" like debian based?

pacman -Qdt

Give what you have. To someone, it may be better than you dare to think.

Offline
#3 2008-06-11 12:54:13

FreakGuard
    Member
    Registered: 2008-04-27
    Posts: 86

Re: how i can "apt-get autoremove" and "autoclean" like debian based?

pacman -R $(pacman -Qdtq)

Offline
#4 2008-06-11 13:02:01

sniffles
    Member
    Registered: 2008-01-23
    Posts: 275

Re: how i can "apt-get autoremove" and "autoclean" like debian based?

BTW: With Arch, you don't have to! (TM) Or that's the impression I have anyway. See the remove options, there are flags which basically allow you to remove 'unneeded' stuff -when- it becomes unneeded.

For example:

Debian:
apt-get install sniffles - also installs libsniffle, libsniffle-dev
apt-get --purge remove sniffles - leaves libsniffle, libsniffle-dev which then have to be removed via autoremove. I'm not sure under what circumstances this won't even work and you'll end up having to use deborphan or somesuch

Arch:
pacman -S sniffles - also installs libsniffle, libsniffle-dev
pacman -Rcns sniffles - also removes libsniffle and libsniffle-dev

Perfect operating system:
<package manager> <install option> sniffles - laughs and blames it on temporary insanity that you'd want to install anything having anything to do with sniffles.

Offline
#5 2008-06-11 16:28:11

underpenguin
    Member
    Registered: 2007-02-01
    Posts: 116

Re: how i can "apt-get autoremove" and "autoclean" like debian based?

If you just want to remove all packages in your cache (= autoclean AFAIK),

pacman -Scc

Last edited by underpenguin (2008-06-11 16:28:45)

Offline
#6 2008-06-11 17:00:08

Ramses de Norre
    Member
    From: Leuven - Belgium
    Registered: 2007-03-27
    Posts: 1,289

Re: how i can "apt-get autoremove" and "autoclean" like debian based?
underpenguin wrote:

    If you just want to remove all packages in your cache (= autoclean AFAIK),

    pacman -Scc

That does what aptitude clean does, the autoclean is equal to pacman -Sc.

Offline
#7 2008-06-11 19:35:42

fuscia
    Member
    Registered: 2008-04-21
    Posts: 398

Re: how i can "apt-get autoremove" and "autoclean" like debian based?
wonder wrote:

    pacman -Qdt

nice.

Offline
#8 2008-06-12 05:38:33

indoultimate
    Member
    Registered: 2008-06-10
    Posts: 9

Re: how i can "apt-get autoremove" and "autoclean" like debian based?

thank u for all your
reply......

Offline
#9 2009-02-27 15:06:48

jazz452
    Member
    Registered: 2008-07-29
    Posts: 21

Re: how i can "apt-get autoremove" and "autoclean" like debian based?

sudo pacman -R $(pacman -Qdtq)

Even better by FreakGuard

Offline
#10 2009-02-27 18:05:51

Inxsible
    Forum Fellow
    From: Chicago
    Registered: 2008-06-09
    Posts: 9,133

Re: how i can "apt-get autoremove" and "autoclean" like debian based?
jazz452 wrote:

    sudo pacman -R $(pacman -Qdtq)

    Even better by FreakGuard

Why dredge up this old thread??

Forum Rules

There's no such thing as a stupid question, but there sure are a lot of inquisitive idiots !

Offline
#11 2018-08-07 10:50:33

gchamon
    Member
    Registered: 2018-08-07
    Posts: 1

Re: how i can "apt-get autoremove" and "autoclean" like debian based?

sorry to dig up this old thread, but to remove recursively the command should be

pacman -Rcs $(pacman -Qdtq)

otherwise, you would have to rerun

pacman -R $(pacman -Qdtq)

until no package shows up, as purged packages in the first run can turn other dependent packages orphans

Offline
#12 2018-08-07 11:10:38

V1del
    Forum Moderator
    Registered: 2012-10-16
    Posts: 10,044

Re: how i can "apt-get autoremove" and "autoclean" like debian based?

Please don't necrobump 10 year old topics.

https://wiki.archlinux.org/index.php/Co … bumping.22

That information has long since been added to the wiki: https://wiki.archlinux.org/index.php/Pa … orphans.29

Closing.

Last edited by V1del (2018-08-07 11:12:58)

Online

Pages: 1

Topic closed

    Index
    » Newbie Corner
    » how i can "apt-get autoremove" and "autoclean" like debian based?

Board footer
Jump to

Atom topic feed

Powered by FluxBB

Constructor | Description
-- | --

**Comment by Sanduhr32** [comment]
yes

**Comment by niklas2810** [comment]
yes
